print("input x & y")
x = int(input())
y = int(input())
print("================================")
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)
print(-x)
print(abs(x))
print(divmod(x, y))
print(x ** y)

print(pow(x, y, 5))
